@startuml
start
:Администратор вводит команду /admin;
if (Токен совпадает?) then (да)
  repeat
  :Появляются команды на выбор:\n1. Посмотреть статистику пользователей\n2. Изменить информацию о пользователе\n3. Выгрузить информацию о пользователях в файл;
  if (Была выбрана команда посмотреть статистику) then (да)
    :Показать статистику пользователей;
  elseif (Была выбрана команда изменить информацию) then (да)
    :Администратор вводит ID пользователя;
    if (Пользователь существует?) then (да)
      :Изменить информацию о пользователе;
    else (нет)
      :Возврат к списку команд;
    endif
  elseif (Была выбрана команда выгрузить в файл) then (да)
    :Администратор вводит имя файла;
    if (Выгрузка успешна?) then (да)
      :Вывод сообщения об успешном завершении операции;
    else (нет)
      :Вывод сообщения об ошибке выполнения операции;
    endif
  endif
  repeat while()
else (нет)
  :Такой команды не существует;
  :Продолжить как обычный пользователь;
  stop
endif
@enduml