@startuml
while (Пользователь активен?) is (да)
start
:Пользователь заходит на бота;
:Бот объясняет свою суть;
repeat
  :Предлагает команды на выбор: /newgame, /help, /balance, /freedemo;
  if (Пользователь выбирает /newgame) then (да)
    :Пользователь выбирает игру;
    repeat
      if (Пользователь играет?) then (да)
        :Пользователь вводит ставку;
        if (Деньги на балансе?) then (да)
          :Запуск игры;
        else (нет)
          :Бот выводит информацию о отсутствии денег;
        endif
      else (нет)
      endif
    repeat while (Пользователь не выбрал новую игру?)
  elseif (Пользователь выбирает /help) then (да)
    :Бот предоставляет информацию о функционале и о себе;
  elseif (Пользователь выбирает /balance) then (да)
    :Бот выводит информацию о балансе пользователя;
  elseif (Пользователь выбирает /freedemo) then (да)
    :Бот предоставляет ограниченное количество денег;
  else
    :Бот не понимает команду;
  endif
repeat while (Пользователь желает продолжить взаимодействие?)
endwhile
stop
@enduml